language: python
python:
  - "3.7"

install: 
  - sudo apt-get install build-essential checkinstall
  - sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev -y
  - cd /usr/src
  - sudo wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz
  - sudo tar xzf Python-3.7.2.tgz
  - cd Python-3.7.2
  - sudo ./configure --enable-optimizations
  - sudo make altinstall
  
  - echo "Aquí se instalan las dependencias"
#   - pip install django

before_script: 
  - echo "Antes de ejecutar un script"

script: 
  - echo "Pruebas unitarias de Calculadora 2019"
  - python Test*.py
  - echo "Finalizar"

notifications:
email: false